// <auto-generated />
using System;
using Core.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AnodeCTX))]
    [Migration("20231213145844_AddedAnodeTypeToShootingPacket")]
    partial class AddedAnodeTypeToShootingPacket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("AlarmC");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsCycle.Models.DB.AlarmCycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmListPacketID")
                        .HasColumnType("int");

                    b.Property<string>("AlarmRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NbNonAck")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmListPacketID");

                    b.ToTable("AlarmCycle");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsLog.Models.DB.AlarmLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAck")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSClear")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSGet")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSRaised")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSRead")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmID");

                    b.ToTable("AlarmLog", t =>
                        {
                            t.HasTrigger("trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmID")
                        .HasColumnType("int");

                    b.Property<string>("IRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NbNonAck")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSClear")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSRaised")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmID")
                        .IsUnique();

                    b.ToTable("AlarmRT");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.Anode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset?>("ClosedTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("S1S2CycleID")
                        .HasColumnType("int");

                    b.Property<string>("S1S2CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S1S2CycleStationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("S1S2CycleTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("S3S4CycleID")
                        .HasColumnType("int");

                    b.Property<int?>("S3S4CycleStationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("S3S4CycleTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("S1S2CycleID")
                        .IsUnique();

                    b.HasIndex("S3S4CycleID")
                        .IsUnique()
                        .HasFilter("[S3S4CycleID] IS NOT NULL");

                    b.ToTable("Anode");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Anode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.BI.BITemperatures.Models.DB.BITemperature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<string>("TemperatureRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BITemperature");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.BenchmarkTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnodeType")
                        .HasColumnType("int");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSIndex")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("CameraID");

                    b.HasIndex("RID");

                    b.HasIndex("TSIndex");

                    b.ToTable("BenchmarkTest");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("CameraTest");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("IOTDevice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IOTDevice");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.IOTTag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("HasNewValue")
                        .HasColumnType("bit");

                    b.Property<int>("IOTDeviceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("IOTDeviceID");

                    b.ToTable("IOTTag");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IOTTag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.KPI.KPICs.Models.DB.KPIC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("KPIC");
                });

            modelBuilder.Entity("Core.Entities.KPI.KPIEntries.Models.DB.KPILogs.KPILog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KPICID")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KPICID");

                    b.ToTable("KPILog");
                });

            modelBuilder.Entity("Core.Entities.KPI.KPIEntries.Models.DB.KPIRTs.KPIRT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KPICID")
                        .HasColumnType("int");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KPICID");

                    b.ToTable("KPIRT");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Packet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("StationCycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Packet");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Packet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.StationCycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AlarmListID")
                        .HasColumnType("int");

                    b.Property<int?>("AlarmListStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AnnouncementID")
                        .HasColumnType("int");

                    b.Property<int?>("AnnouncementStatus")
                        .HasColumnType("int");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DetectionID")
                        .HasColumnType("int");

                    b.Property<int?>("DetectionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShootingID")
                        .HasColumnType("int");

                    b.Property<int?>("ShootingStatus")
                        .HasColumnType("int");

                    b.Property<int>("SignStatus1")
                        .HasColumnType("int");

                    b.Property<int>("SignStatus2")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSClosed")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmListID")
                        .IsUnique()
                        .HasFilter("[AlarmListID] IS NOT NULL");

                    b.HasIndex("AnnouncementID")
                        .IsUnique()
                        .HasFilter("[AnnouncementID] IS NOT NULL");

                    b.HasIndex("DetectionID")
                        .IsUnique()
                        .HasFilter("[DetectionID] IS NOT NULL");

                    b.HasIndex("ShootingID")
                        .IsUnique()
                        .HasFilter("[ShootingID] IS NOT NULL");

                    b.ToTable("StationCycle");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StationCycle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.Act", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActID")
                        .HasColumnType("int");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ActID");

                    b.ToTable("ActEntities");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntityRoles.ActEntityRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActEntityID")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ActEntityID");

                    b.ToTable("ActEntityRoles");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Roles.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEkium")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Vision.FileSettings.Models.DB.FileSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModification")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUploadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("FileSetting");
                });

            modelBuilder.Entity("Core.Entities.Vision.SignedCycles.Models.DB.LoadableQueues.LoadableQueue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("CycleTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DataSetID")
                        .HasColumnType("int");

                    b.Property<int>("LoadableCycleID")
                        .HasColumnType("int");

                    b.Property<string>("SAN1Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAN2Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("CycleTS");

                    b.HasIndex("LoadableCycleID");

                    b.ToTable("LoadableQueue");
                });

            modelBuilder.Entity("Core.Entities.Vision.SignedCycles.Models.DB.MatchableStacks.MatchableStack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("CycleTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DataSetID")
                        .HasColumnType("int");

                    b.Property<int>("MatchableCycleID")
                        .HasColumnType("int");

                    b.Property<string>("SAN1Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAN2Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("CycleTS");

                    b.HasIndex("MatchableCycleID");

                    b.ToTable("MatchableStack");
                });

            modelBuilder.Entity("Core.Shared.Models.DB.System.Logs.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Api")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("bit");

                    b.Property<string>("Server")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesD20.AnodeD20", b =>
                {
                    b.HasBaseType("Core.Entities.Anodes.Models.DB.Anode");

                    b.HasDiscriminator().HasValue("AnodeD20");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", b =>
                {
                    b.HasBaseType("Core.Entities.Anodes.Models.DB.Anode");

                    b.Property<int?>("S5CycleID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("S5CycleTS")
                        .HasColumnType("datetimeoffset");

                    b.HasIndex("S5CycleID")
                        .IsUnique()
                        .HasFilter("[S5CycleID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("AnodeDX");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.ITApis.ITApi", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("ITApi");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.OTCameras.OTCamera", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("OTCamera");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.OTTwinCats.OTTwinCat", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("OTTwinCat");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.OTTagsTwinCat.OTTagTwinCat", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTTags.Models.DB.IOTTag");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OTTagTwinCat");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.HasDiscriminator().HasValue("AlarmList");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Announcements.Announcement", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<string>("AnnounceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Announcement");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Detections.Detection", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<int>("AnodeSize")
                        .HasColumnType("int");

                    b.Property<bool>("IsSameType")
                        .HasColumnType("bit");

                    b.Property<string>("MeasuredType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Detection");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<int>("BakedConvPos")
                        .HasColumnType("int");

                    b.Property<int>("FTAPlace")
                        .HasColumnType("int");

                    b.Property<int>("FTASuck")
                        .HasColumnType("int");

                    b.Property<int>("GreenConvPos")
                        .HasColumnType("int");

                    b.Property<string>("InAnnounceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginID")
                        .HasColumnType("int");

                    b.Property<int>("PackPosition")
                        .HasColumnType("int");

                    b.Property<int>("PalletSide")
                        .HasColumnType("int");

                    b.Property<int>("PitHeight")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PitLoadTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PitNumber")
                        .HasColumnType("int");

                    b.Property<int>("PitSectionNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("InFurnace");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<DateTimeOffset?>("DepositTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FTAPickUp")
                        .HasColumnType("int");

                    b.Property<int>("InvalidPacket")
                        .HasColumnType("int");

                    b.Property<string>("OutAnnounceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PickUpTS")
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("OutFurnace");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Shootings.Shooting", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<int>("AnodeIDKey")
                        .HasColumnType("int");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalStationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcedurePerformance")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.ToTable("Packet", t =>
                        {
                            t.Property("AnodeType")
                                .HasColumnName("Shooting_AnodeType");
                        });

                    b.HasDiscriminator().HasValue("Shooting");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.LoadableCycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.StationCycle");

                    b.HasDiscriminator().HasValue("LoadableCycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.StationCycle");

                    b.Property<int>("MatchingCamera1")
                        .HasColumnType("int");

                    b.Property<int>("MatchingCamera2")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MatchableCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Announcements.S1S2Announcement.S1S2Announcement", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Announcements.Announcement");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrolleyNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("S1S2Announcement");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Shootings.S3S4Shootings.S3S4Shooting", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Shootings.Shooting");

                    b.Property<bool>("IsDoubleAnode")
                        .HasColumnType("bit");

                    b.ToTable("Packet", t =>
                        {
                            t.Property("AnodeType")
                                .HasColumnName("Shooting_AnodeType");
                        });

                    b.HasDiscriminator().HasValue("S3S4Shooting");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.LoadableCycles.LoadableCycle");

                    b.HasDiscriminator().HasValue("S1S2Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle");

                    b.Property<string>("AnnounceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InFurnaceID")
                        .HasColumnType("int");

                    b.Property<int?>("InFurnaceStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OutFurnaceID")
                        .HasColumnType("int");

                    b.Property<int?>("OutFurnaceStatus")
                        .HasColumnType("int");

                    b.HasIndex("InFurnaceID")
                        .IsUnique()
                        .HasFilter("[InFurnaceID] IS NOT NULL");

                    b.HasIndex("OutFurnaceID")
                        .IsUnique()
                        .HasFilter("[OutFurnaceID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("S3S4Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle");

                    b.HasDiscriminator().HasValue("S5Cycle");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsCycle.Models.DB.AlarmCycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", "AlarmList")
                        .WithMany("AlarmCycles")
                        .HasForeignKey("AlarmListPacketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmList");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsLog.Models.DB.AlarmLog", b =>
                {
                    b.HasOne("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", "Alarm")
                        .WithMany("AlarmLogs")
                        .HasForeignKey("AlarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", b =>
                {
                    b.HasOne("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", "Alarm")
                        .WithOne("AlarmRT")
                        .HasForeignKey("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", "AlarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.Anode", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", "S1S2Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.Anode", "S1S2CycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "S3S4Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.Anode", "S3S4CycleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("S1S2Cycle");

                    b.Navigation("S3S4Cycle");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.BenchmarkTest", b =>
                {
                    b.HasOne("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", "CameraTest")
                        .WithMany("BenchmarkTests")
                        .HasForeignKey("CameraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CameraTest");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.IOTTag", b =>
                {
                    b.HasOne("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", "IOTDevice")
                        .WithMany("IOTTags")
                        .HasForeignKey("IOTDeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IOTDevice");
                });

            modelBuilder.Entity("Core.Entities.KPI.KPIEntries.Models.DB.KPILogs.KPILog", b =>
                {
                    b.HasOne("Core.Entities.KPI.KPICs.Models.DB.KPIC", "KPIC")
                        .WithMany("LogEntries")
                        .HasForeignKey("KPICID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KPIC");
                });

            modelBuilder.Entity("Core.Entities.KPI.KPIEntries.Models.DB.KPIRTs.KPIRT", b =>
                {
                    b.HasOne("Core.Entities.KPI.KPICs.Models.DB.KPIC", "KPIC")
                        .WithMany("RTEntries")
                        .HasForeignKey("KPICID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KPIC");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.StationCycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", "AlarmListPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "AlarmListID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Packets.Models.DB.Announcements.Announcement", "AnnouncementPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "AnnouncementID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Packets.Models.DB.Detections.Detection", "DetectionPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "DetectionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Packets.Models.DB.Shootings.Shooting", "ShootingPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "ShootingID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AlarmListPacket");

                    b.Navigation("AnnouncementPacket");

                    b.Navigation("DetectionPacket");

                    b.Navigation("ShootingPacket");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Acts.Act", "Act")
                        .WithMany()
                        .HasForeignKey("ActID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntityRoles.ActEntityRole", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", "ActEntity")
                        .WithMany("ActEntityRoles")
                        .HasForeignKey("ActEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActEntity");
                });

            modelBuilder.Entity("Core.Entities.Vision.SignedCycles.Models.DB.LoadableQueues.LoadableQueue", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.LoadableCycles.LoadableCycle", "LoadableCycle")
                        .WithMany("LoadableQueues")
                        .HasForeignKey("LoadableCycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadableCycle");
                });

            modelBuilder.Entity("Core.Entities.Vision.SignedCycles.Models.DB.MatchableStacks.MatchableStack", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", "MatchableCycle")
                        .WithMany("MatchableStacks")
                        .HasForeignKey("MatchableCycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchableCycle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Roles.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Roles.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", "S5Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", "S5CycleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("S5Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", "InFurnacePacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "InFurnaceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", "OutFurnacePacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "OutFurnaceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("InFurnacePacket");

                    b.Navigation("OutFurnacePacket");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", b =>
                {
                    b.Navigation("AlarmLogs");

                    b.Navigation("AlarmRT")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", b =>
                {
                    b.Navigation("BenchmarkTests");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", b =>
                {
                    b.Navigation("IOTTags");
                });

            modelBuilder.Entity("Core.Entities.KPI.KPICs.Models.DB.KPIC", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("RTEntries");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.Navigation("ActEntityRoles");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", b =>
                {
                    b.Navigation("AlarmCycles");

                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Announcements.Announcement", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Detections.Detection", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Shootings.Shooting", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.LoadableCycle", b =>
                {
                    b.Navigation("LoadableQueues");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", b =>
                {
                    b.Navigation("MatchableStacks");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", b =>
                {
                    b.Navigation("Anode");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.Navigation("Anode");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", b =>
                {
                    b.Navigation("Anode");
                });
#pragma warning restore 612, 618
        }
    }
}
