// <auto-generated />
using System;
using Core.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AnodeCTX))]
    [Migration("20240614154225_RemoveColumnTypeFromSerilogTable")]
    partial class RemoveColumnTypeFromSerilogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("AlarmC");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsCycle.Models.DB.AlarmCycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmListPacketID")
                        .HasColumnType("int");

                    b.Property<string>("AlarmRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmListPacketID");

                    b.ToTable("AlarmCycle");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsLog.Models.DB.AlarmLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAck")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSClear")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSGet")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSRaised")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSRead")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmID");

                    b.ToTable("AlarmLog", t =>
                        {
                            t.HasTrigger("trigger");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AlarmID")
                        .HasColumnType("int");

                    b.Property<string>("IRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSRaised")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmID")
                        .IsUnique();

                    b.ToTable("AlarmRT");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.Anode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("S1S2CycleID")
                        .HasColumnType("int");

                    b.Property<int>("S1S2SignStatus1")
                        .HasColumnType("int");

                    b.Property<int>("S1S2SignStatus2")
                        .HasColumnType("int");

                    b.Property<int?>("S1S2StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("S1S2TSFirstShooting")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("S3S4CycleID")
                        .HasColumnType("int");

                    b.Property<int>("S3S4MatchingCamera2")
                        .HasColumnType("int");

                    b.Property<int>("S3S4SignStatus1")
                        .HasColumnType("int");

                    b.Property<int>("S3S4SignStatus2")
                        .HasColumnType("int");

                    b.Property<int?>("S3S4StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("S3S4TSFirstShooting")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SS3S4MatchingCamera1")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("S1S2CycleID")
                        .IsUnique()
                        .HasFilter("[S1S2CycleID] IS NOT NULL");

                    b.HasIndex("S3S4CycleID")
                        .IsUnique()
                        .HasFilter("[S3S4CycleID] IS NOT NULL");

                    b.ToTable("Anode");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Anode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.BI.BITemperatures.Models.DB.BITemperature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<string>("TemperatureRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BITemperature");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.BenchmarkTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnodeType")
                        .HasColumnType("int");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TSIndex")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("CameraID");

                    b.HasIndex("RID");

                    b.HasIndex("TSIndex");

                    b.ToTable("BenchmarkTest");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("CameraTest");
                });

            modelBuilder.Entity("Core.Entities.DebugsModes.Models.DB.DebugMode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("CsvExportEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("DebugModeEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LogEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LogSeverity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("DebugModes");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("IOTDevice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IOTDevice");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.IOTTag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("HasNewValue")
                        .HasColumnType("bit");

                    b.Property<int>("IOTDeviceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID");

                    b.HasIndex("IOTDeviceID");

                    b.ToTable("IOTTag");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IOTTag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.KPIData.KPIs.Models.DB.KPI", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("ComputeTime")
                        .HasColumnType("bigint");

                    b.Property<int>("MScore")
                        .HasColumnType("int");

                    b.Property<double>("NMAvg")
                        .HasColumnType("float");

                    b.Property<double>("NMStdev")
                        .HasColumnType("float");

                    b.Property<int>("NMmaxScore")
                        .HasColumnType("int");

                    b.Property<int>("NMminScore")
                        .HasColumnType("int");

                    b.Property<int>("NbCandidats")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("KPI");
                });

            modelBuilder.Entity("Core.Entities.KPIData.TenBestMatchs.Models.DB.TenBestMatch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KPIID")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("KPIID");

                    b.ToTable("TenBestMatch");
                });

            modelBuilder.Entity("Core.Entities.KPIData.WarningMsgs.Models.DB.WarningMsg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("KPIID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("KPIID");

                    b.ToTable("WarningMsg");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Packet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("StationCycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TwinCatStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Packet");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Packet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.StationCycle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AlarmListID")
                        .HasColumnType("int");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("HasPlug")
                        .HasColumnType("bit");

                    b.Property<int?>("MetaDataID")
                        .HasColumnType("int");

                    b.Property<int>("NbActiveAlarms")
                        .HasColumnType("int");

                    b.Property<int>("Picture1Status")
                        .HasColumnType("int");

                    b.Property<int>("Picture2Status")
                        .HasColumnType("int");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shooting1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Shooting2ID")
                        .HasColumnType("int");

                    b.Property<int>("SignStatus1")
                        .HasColumnType("int");

                    b.Property<int>("SignStatus2")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TSFirstShooting")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("AlarmListID")
                        .IsUnique()
                        .HasFilter("[AlarmListID] IS NOT NULL");

                    b.HasIndex("MetaDataID")
                        .IsUnique()
                        .HasFilter("[MetaDataID] IS NOT NULL");

                    b.HasIndex("Shooting1ID")
                        .IsUnique()
                        .HasFilter("[Shooting1ID] IS NOT NULL");

                    b.HasIndex("Shooting2ID")
                        .IsUnique()
                        .HasFilter("[Shooting2ID] IS NOT NULL");

                    b.ToTable("StationCycle");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StationCycle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.Act", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActID")
                        .HasColumnType("int");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ActID");

                    b.ToTable("ActEntities");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntityRoles.ActEntityRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActEntityID")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ActEntityID");

                    b.ToTable("ActEntityRoles");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Roles.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEkium")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Vision.Testing.Models.DB.StationTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnodeType")
                        .HasColumnType("int");

                    b.Property<int>("Cam1Status")
                        .HasColumnType("int");

                    b.Property<int>("Cam2Status")
                        .HasColumnType("int");

                    b.Property<bool>("HasPlug")
                        .HasColumnType("bit");

                    b.Property<int>("NbActiveAlarms")
                        .HasColumnType("int");

                    b.Property<string>("Photo1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SN_number")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("StationTests");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.Datasets.Dataset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceMatchID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationCycleID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Dataset");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.ToLoads.ToLoad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceMatchID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationCycleID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("ToLoad");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.ToMatchs.ToMatch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPlug")
                        .HasColumnType("bit");

                    b.Property<int>("InstanceMatchID")
                        .HasColumnType("int");

                    b.Property<int>("NbActiveAlarms")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationCycleID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("ToMatch");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.ToNotifys.ToNotify", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<string>("SynchronisationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("ToNotify");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.ToSigns.ToSign", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPlug")
                        .HasColumnType("bit");

                    b.Property<int>("NbActiveAlarms")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationCycleID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("ToSign");
                });

            modelBuilder.Entity("Core.Entities.Vision.ToDos.Models.DB.ToUnloads.ToUnload", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CycleRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceMatchID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StationCycleID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("ToUnload");
                });

            modelBuilder.Entity("Core.Shared.Models.DB.System.Logs.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Api")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("bit");

                    b.Property<string>("Server")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Core.Shared.Models.DB.System.Logs.LogEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBeenSent")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TS")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesD20.AnodeD20", b =>
                {
                    b.HasBaseType("Core.Entities.Anodes.Models.DB.Anode");

                    b.HasDiscriminator().HasValue("AnodeD20");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", b =>
                {
                    b.HasBaseType("Core.Entities.Anodes.Models.DB.Anode");

                    b.Property<int?>("S5CycleID")
                        .HasColumnType("int");

                    b.Property<int>("S5MatchingCamera1")
                        .HasColumnType("int");

                    b.Property<int>("S5MatchingCamera2")
                        .HasColumnType("int");

                    b.Property<int>("S5SignStatus2")
                        .HasColumnType("int");

                    b.Property<int?>("S5StationID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("S5TSFirstShooting")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SSignStatus1")
                        .HasColumnType("int");

                    b.HasIndex("S5CycleID")
                        .IsUnique()
                        .HasFilter("[S5CycleID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("AnodeDX");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.BackgroundServices.Matchs.Match", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceMatchID")
                        .HasColumnType("int");

                    b.Property<bool>("Pause")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<int>("StationID")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("WatchdogTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("Match");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.BackgroundServices.Signs.Sign", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pause")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit");

                    b.Property<int>("StationID")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("WatchdogTime")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("Sign");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.ITApis.ITApi", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("ITApi");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.OTCameras.OTCamera", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("OTCamera");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.OTTwinCats.OTTwinCat", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.HasDiscriminator().HasValue("OTTwinCat");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.ServerRules.ServerRule", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice");

                    b.Property<bool>("Reinit")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("ServerRule");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.OTTagsTwinCat.OTTagTwinCat", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTTags.Models.DB.IOTTag");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OTTagTwinCat");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.HasDiscriminator().HasValue("AlarmList");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<int>("FTAPlace")
                        .HasColumnType("int");

                    b.Property<int>("GreenConvPos")
                        .HasColumnType("int");

                    b.Property<string>("InAnnounceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginID")
                        .HasColumnType("int");

                    b.Property<int>("PackPosition")
                        .HasColumnType("int");

                    b.Property<int>("PalletSide")
                        .HasColumnType("int");

                    b.Property<int>("PitHeight")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PitLoadTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PitNumber")
                        .HasColumnType("int");

                    b.Property<int>("PitSectionNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("InFurnace");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<int>("BakedConvPos")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DepositTS")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FTAPickUp")
                        .HasColumnType("int");

                    b.Property<int>("InvalidPacket")
                        .HasColumnType("int");

                    b.Property<string>("OutAnnounceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PickUpTS")
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("OutFurnace");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.MetaDatas.MetaData", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<float>("AnodeSize")
                        .HasColumnType("real");

                    b.Property<int>("AnodeTypeStatus")
                        .HasColumnType("int");

                    b.Property<int>("AnodeType_MD")
                        .HasColumnType("int");

                    b.Property<int>("AnodeType_RW")
                        .HasColumnType("int");

                    b.Property<int>("Cam01Status")
                        .HasColumnType("int");

                    b.Property<float>("Cam01Temp")
                        .HasColumnType("real");

                    b.Property<int>("Cam02Status")
                        .HasColumnType("int");

                    b.Property<float>("Cam02Temp")
                        .HasColumnType("real");

                    b.Property<int>("Double_RW")
                        .HasColumnType("int");

                    b.Property<int>("NbActiveAlarms")
                        .HasColumnType("int");

                    b.Property<int>("SN_Day")
                        .HasColumnType("int");

                    b.Property<int>("SN_Month")
                        .HasColumnType("int");

                    b.Property<int>("SN_Number")
                        .HasColumnType("int");

                    b.Property<int>("SN_StationID")
                        .HasColumnType("int");

                    b.Property<int>("SN_Vibro")
                        .HasColumnType("int");

                    b.Property<int>("SN_Year")
                        .HasColumnType("int");

                    b.Property<int>("SyncIndex")
                        .HasColumnType("int");

                    b.Property<int>("SyncIndex_RW")
                        .HasColumnType("int");

                    b.Property<float>("TT01")
                        .HasColumnType("real");

                    b.Property<int>("Trolley")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MetaData");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Shootings.Shooting", b =>
                {
                    b.HasBaseType("Core.Entities.Packets.Models.DB.Packet");

                    b.Property<string>("AnodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cam01Status")
                        .HasColumnType("int");

                    b.Property<int>("Cam02Status")
                        .HasColumnType("int");

                    b.Property<bool>("HasFirstShoot")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPlug")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSecondShoot")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ShootingTS")
                        .HasColumnType("datetimeoffset");

                    b.ToTable("Packet", t =>
                        {
                            t.Property("Cam01Status")
                                .HasColumnName("Shooting_Cam01Status");

                            t.Property("Cam02Status")
                                .HasColumnName("Shooting_Cam02Status");
                        });

                    b.HasDiscriminator().HasValue("Shooting");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.StationCycle");

                    b.HasDiscriminator().HasValue("S1S2Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.StationCycle");

                    b.Property<int?>("KPIID")
                        .HasColumnType("int");

                    b.Property<int>("MatchingCamera1")
                        .HasColumnType("int");

                    b.Property<int>("MatchingCamera2")
                        .HasColumnType("int");

                    b.Property<bool>("MatchingResult")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("MatchingTS")
                        .HasColumnType("datetimeoffset");

                    b.HasIndex("KPIID")
                        .IsUnique()
                        .HasFilter("[KPIID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("MatchableCycle");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.ITApiStations.ITApiStation", b =>
                {
                    b.HasBaseType("Core.Entities.IOT.IOTDevices.Models.DB.ITApis.ITApi");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OldestTSShooting")
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("ITApiStation");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle");

                    b.Property<string>("AnnounceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InFurnaceID")
                        .HasColumnType("int");

                    b.Property<int?>("OutFurnaceID")
                        .HasColumnType("int");

                    b.HasIndex("InFurnaceID")
                        .IsUnique()
                        .HasFilter("[InFurnaceID] IS NOT NULL");

                    b.HasIndex("OutFurnaceID")
                        .IsUnique()
                        .HasFilter("[OutFurnaceID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("S3S4Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", b =>
                {
                    b.HasBaseType("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle");

                    b.Property<int?>("ChainCycleID")
                        .HasColumnType("int");

                    b.Property<int>("ChainMatchingCamera1")
                        .HasColumnType("int");

                    b.Property<int>("ChainMatchingCamera2")
                        .HasColumnType("int");

                    b.Property<bool>("ChainMatchingResult")
                        .HasColumnType("bit");

                    b.HasIndex("ChainCycleID")
                        .IsUnique()
                        .HasFilter("[ChainCycleID] IS NOT NULL");

                    b.HasDiscriminator().HasValue("S5Cycle");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsCycle.Models.DB.AlarmCycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", "AlarmList")
                        .WithMany("AlarmCycles")
                        .HasForeignKey("AlarmListPacketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmList");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsLog.Models.DB.AlarmLog", b =>
                {
                    b.HasOne("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", "Alarm")
                        .WithMany("AlarmLogs")
                        .HasForeignKey("AlarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", b =>
                {
                    b.HasOne("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", "Alarm")
                        .WithOne("AlarmRT")
                        .HasForeignKey("Core.Entities.Alarms.AlarmsRT.Models.DB.AlarmRT", "AlarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.Anode", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", "S1S2Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.Anode", "S1S2CycleID");

                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "S3S4Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.Anode", "S3S4CycleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("S1S2Cycle");

                    b.Navigation("S3S4Cycle");
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.BenchmarkTest", b =>
                {
                    b.HasOne("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", "CameraTest")
                        .WithMany("BenchmarkTests")
                        .HasForeignKey("CameraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CameraTest");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTTags.Models.DB.IOTTag", b =>
                {
                    b.HasOne("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", "IOTDevice")
                        .WithMany("IOTTags")
                        .HasForeignKey("IOTDeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IOTDevice");
                });

            modelBuilder.Entity("Core.Entities.KPIData.TenBestMatchs.Models.DB.TenBestMatch", b =>
                {
                    b.HasOne("Core.Entities.KPIData.KPIs.Models.DB.KPI", "KPI")
                        .WithMany("TenBestMatches")
                        .HasForeignKey("KPIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KPI");
                });

            modelBuilder.Entity("Core.Entities.KPIData.WarningMsgs.Models.DB.WarningMsg", b =>
                {
                    b.HasOne("Core.Entities.KPIData.KPIs.Models.DB.KPI", "KPI")
                        .WithMany("WarningMsgs")
                        .HasForeignKey("KPIID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KPI");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.StationCycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", "AlarmListPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "AlarmListID");

                    b.HasOne("Core.Entities.Packets.Models.DB.MetaDatas.MetaData", "MetaDataPacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "MetaDataID");

                    b.HasOne("Core.Entities.Packets.Models.DB.Shootings.Shooting", "Shooting1Packet")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "Shooting1ID");

                    b.HasOne("Core.Entities.Packets.Models.DB.Shootings.Shooting", "Shooting2Packet")
                        .WithOne("StationCycleShooting2")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.StationCycle", "Shooting2ID");

                    b.Navigation("AlarmListPacket");

                    b.Navigation("MetaDataPacket");

                    b.Navigation("Shooting1Packet");

                    b.Navigation("Shooting2Packet");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Acts.Act", "Act")
                        .WithMany()
                        .HasForeignKey("ActID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntityRoles.ActEntityRole", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", "ActEntity")
                        .WithMany("ActEntityRoles")
                        .HasForeignKey("ActEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Roles.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Roles.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.User.Models.DB.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", "S5Cycle")
                        .WithOne("Anode")
                        .HasForeignKey("Core.Entities.Anodes.Models.DB.AnodesDX.AnodeDX", "S5CycleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("S5Cycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", b =>
                {
                    b.HasOne("Core.Entities.KPIData.KPIs.Models.DB.KPI", "KPI")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.MatchableCycle", "KPIID");

                    b.Navigation("KPI");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.HasOne("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", "InFurnacePacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "InFurnaceID");

                    b.HasOne("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", "OutFurnacePacket")
                        .WithOne("StationCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "OutFurnaceID");

                    b.Navigation("InFurnacePacket");

                    b.Navigation("OutFurnacePacket");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", b =>
                {
                    b.HasOne("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", "ChainCycle")
                        .WithOne("ChainCycle")
                        .HasForeignKey("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", "ChainCycleID");

                    b.Navigation("ChainCycle");
                });

            modelBuilder.Entity("Core.Entities.Alarms.AlarmsC.Models.DB.AlarmC", b =>
                {
                    b.Navigation("AlarmLogs");

                    b.Navigation("AlarmRT")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.BenchmarkTests.Models.DB.CameraTests.CameraTest", b =>
                {
                    b.Navigation("BenchmarkTests");
                });

            modelBuilder.Entity("Core.Entities.IOT.IOTDevices.Models.DB.IOTDevice", b =>
                {
                    b.Navigation("IOTTags");
                });

            modelBuilder.Entity("Core.Entities.KPIData.KPIs.Models.DB.KPI", b =>
                {
                    b.Navigation("StationCycle")
                        .IsRequired();

                    b.Navigation("TenBestMatches");

                    b.Navigation("WarningMsgs");
                });

            modelBuilder.Entity("Core.Entities.User.Models.DB.Acts.ActEntities.ActEntity", b =>
                {
                    b.Navigation("ActEntityRoles");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.AlarmLists.AlarmList", b =>
                {
                    b.Navigation("AlarmCycles");

                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.InFurnaces.InFurnace", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Furnaces.OutFurnaces.OutFurnace", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.MetaDatas.MetaData", b =>
                {
                    b.Navigation("StationCycle");
                });

            modelBuilder.Entity("Core.Entities.Packets.Models.DB.Shootings.Shooting", b =>
                {
                    b.Navigation("StationCycle");

                    b.Navigation("StationCycleShooting2");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.LoadableCycles.S1S2Cycles.S1S2Cycle", b =>
                {
                    b.Navigation("Anode");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S3S4Cycles.S3S4Cycle", b =>
                {
                    b.Navigation("Anode");

                    b.Navigation("ChainCycle");
                });

            modelBuilder.Entity("Core.Entities.StationCycles.Models.DB.MatchableCycles.S5Cycles.S5Cycle", b =>
                {
                    b.Navigation("Anode");
                });
#pragma warning restore 612, 618
        }
    }
}
