# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PiplineCI/CD

on:
  push:
    branches: [ "ATS_AnisDevOps" ]
  pull_request:
    branches: [ "ATS_AnisDevOps" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean & Install
      run: dotnet restore

    - name: Building
      run: dotnet test --no-build --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build & push all images
      run: |
        docker build -t anisammar11/dockerimage:ApiMonitorimage -f ./ApiMonitor/Dockerfile .
        docker push anisammar11/dockerimage:ApiMonitorimage

        docker build -t anisammar11/dockerimage:ApiStationCycleimage -f ./ApiStationCycle/Dockerfile .
        docker push anisammar11/dockerimage:ApiStationCycleimage

        docker build -t anisammar11/dockerimage:ApiKPIimage -f ./ApiKPI/Dockerfile .
        docker push anisammar11/dockerimage:ApiKPIimage

        docker build -t anisammar11/dockerimage:ApiADSimage -f ./ApiADS/Dockerfile .
        docker push anisammar11/dockerimage:ApiADSimage

        docker build -t anisammar11/dockerimage:ApiAlarmimage -f ./ApiAlarm/Dockerfile .
        docker push anisammar11/dockerimage:ApiAlarmimage

        docker build -t anisammar11/dockerimage:ApiIOTimage -f ./ApiIOT/Dockerfile .
        docker push anisammar11/dockerimage:ApiIOTimage

        docker build -t anisammar11/dockerimage:ApiUserimage -f ./ApiUser/Dockerfile .
        docker push anisammar11/dockerimage:ApiUserimage

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: anisammar11/dockerimage:ApiMonitorimage

